server:
  port: 8086
spring:
  application:
    name: rac-simulation-service
  config:
    import: optional:configserver:http://localhost:8888

logging:
  level:
    pl.mg.rac: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'