server:
  port: 8086
spring:
  data:
    mongodb:
      database: rac-simulation
      host: localhost
      port: 27017
  application:
    name: rac-simulation-service
  config:
    import: optional:configserver:http://localhost:8888
logging:
  level:
    pl.mg.rac: DEBUG



## Discovery Service
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


## Actuator
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always