version: '3.8'

services:
  rac-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.4
    container_name: rac-elasticsearch
    environment:
      - discovery.type=single-node
    networks:
      - rac-network
    ports:
      - "9200:9200"
    volumes:
      - /var/lib/docker/volumes/rac/elasticsearch-data:/usr/share/elasticsearch/data

  rac-kibana:
    image: docker.elastic.co/kibana/kibana:8.10.4
    container_name: rac-kibana
    networks:
      - rac-network
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://rac-elasticsearch:9200

volumes:
  elasticsearch-data:
    driver: local

networks:
  rac-network: