server:
  port: 8081

spring:
  application:
    name: rac-user-service

## Discovery Service
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

## Actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
