package pl.mg.rac.commons.event;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

import java.util.HashMap;
import java.util.Map;

@Getter
@RequiredArgsConstructor
public enum EventType {

    //USER EVENTS
    RAC_USER_CREATED("RAC_USER_CREATED"),
    RAC_USER_DELETED("RAC_USER_DELETED"),
    RAC_USER_CHARGED("RAC_USER_CHARGED"),

    //CAR EVENTS
    RAC_CAR_CREATED("RAC_CAR_CREATED"),
    RAC_CAR_DELETED("RAC_CAR_DELETED"),
    RAC_CAR_RENT_SUCCESS("RAC_CAR_RENT_SUCCESS"),
    RAC_CAR_RENT_FAILED_ALREADY_RENTED("RAC_CAR_RENT_FAILED_ALREADY_RENTED"),
    RAC_CAR_RENT_FAILED_NOT_EXISTS("RAC_CAR_RENT_FAILED_NOT_EXISTS"),
    RAC_CAR_RETURN_SUCCESS("RAC_CAR_RETURN_SUCCESS"),
    RAC_CAR_RETURN_FAILED_ALREADY_RETURNED("RAC_CAR_RETURN_FAILED_ALREADY_RETURNED"),
    RAC_CAR_RETURN_FAILED_NOT_EXIST("RAC_CAR_RETURN_FAILED_NOT_EXIST"),

    //RENT EVENTS
    RAC_RENT_REQUEST_USER("RAC_RENT_REQUEST_USER"),
    RAC_RENT_REQUEST_CAR("RAC_RENT_REQUEST_CAR"),
    RAC_RENT_CONFIRMATION("RAC_RENT_CONFIRMATION"),
    RAC_RENT_SUCCESS("RAC_RENT_SUCCESS"),
    RAC_RENT_FAILED_USER("RAC_RENT_FAILED_USER"),
    RAC_RENT_FAILED_CAR("RAC_RENT_FAILED_CAR"),

    //RETURN EVENTS
    RAC_RETURN_REQUEST_LOCATION("RAC_RETURN_REQUEST_LOCATION"),
    RAC_RETURN_REQUEST_USER("RAC_RETURN_REQUEST_USER"),
    RAC_RETURN_REQUEST_CAR("RAC_RETURN_REQUEST_CAR"),
    RAC_RETURN_CONFIRMATION("RAC_RETURN_CONFIRMATION"),
    RAC_RETURN_SUCCESS("RAC_RETURN_SUCCESS"),
    RAC_RETURN_FAILED_LOCATION("RAC_RETURN_FAILED_LOCATION"),
    RAC_RETURN_FAILED_USER("RAC_RETURN_FAILED_USER"),
    RAC_RETURN_FAILED_CAR("RAC_RETURN_FAILED_CAR"),

    //LOCATION CHANGE EVENTS
    RAC_LOCATION_USER_CHANGED("RAC_LOCATION_USER_CHANGED"),
    RAC_LOCATION_CAR_CHANGED("RAC_LOCATION_CAR_CHANGED"),
    ;

    private final String id;

    private static final Map<String, EventType> BY_ID = new HashMap<>();

    static {
        for (EventType eventType : values()) {
            BY_ID.put(eventType.id, eventType);
        }
    }

    public static EventType of(String id) {
        EventType eventType = BY_ID.get(id);
        if (eventType == null) {
            throw new IllegalArgumentException("No EventType with id " + id + " found");
        }
        return eventType;
    }

}
